(define (problem monkey1)
    (:domain MonkeyForBananas)
    (:objects m bx t sci b pos1 pos2 pos3 pos4)
    (:init  (monkey m)
            (box bx)
            (bananas b)
            (scissors sci)
            (table t)
            (pos pos1)
            (pos pos2)
            (pos pos3)
            (pos pos4)
            (at m pos1)
            (at b pos2)
            (at bx pos3)
            (at t pos4)
            (at sci pos4)
            (on sci t))
    (:goal (has m b))
)
