(define (problem wsc1)
    (:domain WolfSheepCabbage)
    (:objects w sh c s1 s2 m)
    (:init  (wolf w)
            (sheep sh)
            (cabbage c)
            (man m)
            (side s1)
            (side s2)
            (at w s1)
            (at sh s1)
            (at c s1)
            (at m s1)
            )
    (:goal (and (at w s2)
            (at sh s2)
            (at m s2)
            (at c s2)))
)